name = "EscapeAnalysis"
uuid = "c6a77b2f-5d97-4bf0-b260-35fa9cc0f3d0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]
version = "0.0.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
